[package]
name = "application"
version = "0.1.0"
edition = "2021"
publish = false

[dependencies]
engine = { path = "../engine/" }

winit = "0.28.2"
mimalloc = { version = "0.1.36", default-features = false }
